### ISSUE TITLE
Miscellaneous Courses not showing after back

### ISSUE THREAD

**Issue by itsomkathe** [navgurukul/bhanwari-devi#598]
Miscellaneous Courses page is not showing after clicked back.
[Refer this video
](https://drive.google.com/file/d/1T3rn8Nvfr6DlDuxnWpMqAJJIZL0p4tyo/view)

**Refer Sheet:**
Student is logged in (website), Test Case 4.3

**Comment by itsomkathe** [comment]
After debugging, this certainly looks like an issue with Redux Saga.

**Comment by jschanker** [comment]
@itsomkathe I'm getting an Access Denied when trying to click on the video link, but I was able to reproduce the error. It occurs earlier after clicking on any course in `/open-course`. (Then, the problem will occur after you click on the back button or the `x` in the top left corner to go back.) The issue is that a bad request is made to `https://api.merakilearn.org/pathways/miscellaneous/enrolledBatches`: 

This is a bad request because the back-end is expecting an integer for the pathway id but `miscellaneous` is being used:

https://github.com/navgurukul/sansaar/blob/main/lib/routes/pathways.js#L1282-L1294:

```
    method: 'GET',
    path: '/pathways/{pathwayId}/enrolledBatches',
    options: {
      description: 'Gets a list of all upcoming enrolled batch in a pathways',
      tags: ['api'],
      auth: {
        strategy: 'jwt',
      },
      validate: {
        params: Joi.object({
          pathwayId: Joi.number().integer().required(),
        }),
      },
```
Looking through the stack trace for the reference to the relevant code that causes this bad request:

![image](https://user-images.githubusercontent.com/9159008/186264094-e9e2e33d-2dfa-45df-88cb-0e811004c23c.png)

we can see it's the API call made here:

![image](https://user-images.githubusercontent.com/9159008/186264404-e3d2c441-1fe1-4183-821f-ef4a58a6d903.png)

So, `pathwayId` is `miscellaneous` here, but this comes from the value of the `data` key from the dispatched action. So, going down the stack trace even more, we can find the reference to the dispatched action causing the problem:

![image](https://user-images.githubusercontent.com/9159008/186265336-4ad2a2f2-6eaf-439e-b5d1-8492ae796550.png)

And here is the code:

![image](https://user-images.githubusercontent.com/9159008/186263646-ae69c066-9653-4ecf-9635-944adecebadf.png)

And `pathwayId` is assigned above here:

![image](https://user-images.githubusercontent.com/9159008/186267996-320e52ce-f6d7-40f7-878b-e2537dbd6b07.png)

So, the issue is occurring because unlike the Python, Typing, and Spoken English pathways, there is no numerical pathway id.  This will also be a problem with the Residential courses.

**Comment by kartiks26** [comment]
.

**Comment by jschanker** [comment]
@kartiks26 `Number.isInteger` would work too, you just need to cast `pathwayId` to a number first since the parameter value will be a `string`.  So, something like `Number.isInteger(Number(pathwayId))` or even just `Number.isInteger(+pathwayId)` would work.
