### ISSUE TITLE
Exercise Navigation: Images for completed assessments not visible

### ISSUE THREAD

**Issue by itsomkathe** [navgurukul/bhanwari-devi#632]
**Description**

On the `/course-content`, even if the assessment, class, or exercise has been completed, the image of completed is not getting displayed. Instead, the normal image (say `assessment.svg`, etc) is shown. 
The thing is, the logic for selecting is correct and for each `contentType`, it logs the correct mapped image. But on runtime, it changes the `src`. This can be seen by inspecting.

**Use the branch `LearningTrackUpdate`**

`console.log` for `id` of `contentType`. The boolean value represents if the particular type is completed or not. The corresponding file name is generated correctly using `contentTypeMap` logic.

![Capture](https://user-images.githubusercontent.com/34516916/187023682-53df1796-fbcb-4f6a-9c1f-d4bc1d7659aa.PNG)

Below you can see the `src` has been changed for.

![Capture2](https://user-images.githubusercontent.com/34516916/187023854-bb5b4a16-0f5e-466f-aa19-800c574dcfe7.PNG)

**Comment by itsomkathe** [comment]
@jschanker can you take a look please?

**Comment by jschanker** [comment]
@itsomkathe You were seeing the logs for the `ExerciseImage`s for mobile:
https://github.com/navgurukul/bhanwari-devi/blob/8ad3cac0fb259fd1fc8e51439fb61c07bc105b5b/src/components/PathwayExercise/index.js#L412-L419

The first ones coming from the child `ExerciseImage` of `NavigationComponent`, which were children of the `Exercise` Component:
https://github.com/navgurukul/bhanwari-devi/blob/8ad3cac0fb259fd1fc8e51439fb61c07bc105b5b/src/components/PathwayExercise/index.js#L80-L95 
were missing an `id` prop, which is why you got the following: 
```
For id undefined   false  and file  assessment
ExerciseImage.js:46 For id undefined   false  and file  contenttype
ExerciseImage.js:46 For id undefined   false  and file  assessment
ExerciseImage.js:46 For id undefined   false  and file  assessmentSelected
2ExerciseImage.js:46 For id undefined   false  and file  assessment
```
I added it in in this [commit](https://github.com/navgurukul/bhanwari-devi/pull/634/commits/0ca34cc72b3a939be5a21837918096872d9acaf6) so I could check that it worked and all seems to be good on `sdev-meraki` although @kartiks26 , once again there seems to be a deployment error for `bhanwari-devi`.
