### ISSUE TITLE
NavBars of different roles not displaying expected items

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#659]
**Describe the bug**
NavBar of Admin, Volunteer & Partner dashboards not working as expected

**To Reproduce**
Login as Admin, Volunteer & Partner one by one

**Expected behaviour**
The NavBars should show the relevant items for each role

**Screencasts**
1. [For Admin](https://drive.google.com/file/d/1qe5bGPZZbDJQ4qbHFeuDapW-U9BxrKKj/view?usp=sharing)
2. [For Partner](https://drive.google.com/file/d/1G4i-a9KHML9l-5y7f26G9dgKtCdWarAo/view?usp=sharing)
3. [For Volunteer](https://drive.google.com/file/d/1VregxOjJdkKZutL3y23tcIGCavC8f_fI/view?usp=sharing)

**Refer Sheet**
Weekly Testing Bugs, Test Case 1

**Comment by jschanker** [comment]
The issue is that your last selected role is being stored in `localStorage` and when you login or refresh the page, it shows the navigation items for this role. So, this should only be a problem when (1) you login with an account that doesn't have that role as you showed in your screencasts or when (2) you remove a role from a user,

We can fix (1) by associating selected roles with account e-mail addresses in `localStorage` and (2) by checking if the user still has that role before showing the last selected role's navigation items.

**Comment by saquibaijaz** [comment]
@Poonam-Singh-Bagh please check
