### ISSUE TITLE
(Production Bug) Broken images for Spoken English course modules

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#752]
**To Reproduce**
1. Go to the prod website for Meraki
2. Goto Spoken English section
3. Course module images are broken

**Expected behavior**
Correct images should show up for the course modules

![production bug](https://user-images.githubusercontent.com/111858763/195837254-fbe828de-04e5-4d12-a3c4-f323ae2fc165.png)

**Comment by komalahire** [comment]
@saquibaijaz 

These images should come from the backend. I am coordinating with the backend for the same. Will change the status whenever they do this.

**Comment by saquibaijaz** [comment]
@komalahire 
Please tell the backend to take it as Highest Priority, as this is in production.

**Comment by komalahire** [comment]
Narendra suggested that we would not add images to that course because we have the main course SPOKEN ENGLISH only.
And that all are Supplemental courses with no need for images. 

We are going to show somthing like this.
![Screenshot 2022-10-17 185702](https://user-images.githubusercontent.com/43803182/196189627-c4f9ad48-81c9-4240-84d7-a108be5daaa1.png)

I am working on it. It will be completed tonight.

**Comment by Poonam-Singh-Bagh** [comment]
Done...!

**Comment by saquibaijaz** [comment]
![Untitled](https://user-images.githubusercontent.com/111858763/196347068-dc61b0c0-27ff-4814-a41a-e21ec957e96e.png)

It's fine. Just a little change is needed.

**Comment by Poonam-Singh-Bagh** [comment]
What change is needed @saquibaijaz?

**Comment by saquibaijaz** [comment]
Check the attached pic
@Poonam-Singh-Bagh

**Comment by kartiks26** [comment]
@kirithiv2000

**Comment by kirithiv2000** [comment]
fixed
