### ISSUE TITLE
Search Feature on Back Not Working Properly

### ISSUE THREAD

**Issue by itsomkathe** [navgurukul/bhanwari-devi#789]
**Describe the bug**
The search component on the header, when removing the text and clicking on the back button, again searches the previous query.

**Expected behavior**
After clicking on the back button it should go to the previous page.

**Comment by jschanker** [comment]
@itsomkathe It seems to me that we would want to preserve this behavior, at least partially. For example, if the user typed in `python`, hit the Enter key and then typed in `english`, then if they clicked on the back button, we'd want them to go back to get the search results for `python`, right? If so, this should be an easy fix, mainly only `push` to the history when the value of the `key` property of the event is [`Enter`](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#whitespace_keys). We should also centralize search/filter functionality as described in https://github.com/navgurukul/bhanwari-devi/issues/776 so the functionality for different searches remains consistent.

**Comment by itsomkathe** [comment]
@jschanker But after every change in the textfield it pushes the word in history so that we make a GET request. So there is no need to hit enter for user. And yes the centralisation is under consideration. So as of now I will fix this as you are saying ie. Search only after enter key.

**Comment by jschanker** [comment]
I'm not sure about what's best from a user's standpoint. It seems desirable to show matches with each key stroke so I'm not sure that we'd want to wait for the Enter key to be hit before we show the search results. On the other hand, if we show search results as the user types, they're less likely to hit the Enter key. As I'm sure you've seen, Google handles this by providing a dropdown of suggestions. In this case, the user is encouraged to hit the Enter key because in that case they will see a page of results and their search will get pushed to the browser history. So, we could do something similar here, but I don't know whether that's what we'd want for courses or not?

With respect to course searches, there is only one GET request to retrieve all of them and then the courses are filtered on the front-end. If there is only a small amount of data involved, this is the way to go as it avoids unnecessary requests to the back-end that decrease performance. On the other hand, if the data is large, we probably would not want to do this as there's a steep upfront cost in that initial request to get all data. The way to handle that I think, is to instead limit the results of any search and have the user click (or scroll down) to get more. For example, for each key stroke, Google makes an API request where the response only contains 10 search results and when the user clicks Enter, it seems to be about 19 to get the page of results. To keep things fast, we should probably do something similar, but we should try to provide the most relevant results.

However, currently, we're making the request to get **all volunteers** for the Tutor Dashboard, so it doesn't seem beneficial to make subsequent requests for all volunteers based on filters. Instead, we should as we do with the course search, be filtering on the front-end, which should improve performance.

**Comment by itsomkathe** [comment]
I've changed `history.push` to `history.replace`  as of now, as the latter is working better. 
Later we will be implementing the search as per #776. I think we can find a better solution for this by discussing it with the UX/Product team.
